### ISSUE TITLE
apigeectl and asm are not up to date

### ISSUE THREAD

**Issue by rohan-199** [yuriylesyuk/ahr#5]
you are using apigeectl and asm older version you can also automate that part also

**Comment by OmidTahouri** [comment]
As per the notices in the [README](https://github.com/yuriylesyuk/ahr/blob/c9a9dd125b94222668b12634d9944347b61b7c70/README.md) and [wiki](https://github.com/yuriylesyuk/ahr/wiki), **please refer to the [apigee/ahr](https://github.com/apigee/ahr) repository where this project is now maintained**.
